### ISSUE TITLE
Publish Cliqz Browser in Snapstore for Linux

### ISSUE THREAD

**Issue by gurgunday** [cliqz-oss/browser-f#1432]
Hi everyone! I know Cliqz for Linux is not a priority at the moment but I suggest adding it to the [Snap Store](https://snapcraft.io/store) for a simple coverage of all Linux distributions. It would both benefit you as you wouldn't need to keep a PPA and us who wish to easily download Cliqz on Linux devices.

**Comment by remusao** [comment]
Hi @gurgunday,

Snap is something we experimented with a (long) while ago. At the time it was not ready for prime-time. It is probably more mature now and we could give it another shot :)

Thanks for the suggestion,

**Comment by gurgunday** [comment]
To add to the issue, I also think if you don’t want to use a centralized store and want your website to be the only source to download Cliqz Browser, AppImage is a great alternative that works on most (if not all) Linux distributions.

**Comment by remusao** [comment]
Thanks for the suggestion. There seems to be a few contenders with regard to packaging: snap, flatpak and appimage. It is not clear to me at this point if one of them is "the winner". Ideally it would be nice if one stack becomes the de-factor standard, otherwise there will be a lot of fragmentation in the ecosystem and we don't win much compared to the `deb`/`rpm` situation.

**Comment by ghost** [comment]
Well, I would also love to see a single, fully adopted standard!

Forgive me if I’m writing things that you already know but I want to elaborate a little since all decisions made by the Cliqz team have real good reasoning behind them and even though this subject, in particular, seems to be one where there will never be a clear winner, we shouldn't consider every Linux user technically advanced enough to know how to use the terminal. This may not sound that realistic at first but there are genuine people that use Linux around me and would rather download Cliqz Browser as an AppImage from your site or as a snap. They just don't want to use the terminal as they are afraid that they can break things. It would also increase the value proposition as causal people on Linux would have to do less work to get your apps.

One other argument is that they are more "fail-safe" than deb packages since none of them require root privileges to work. A bug in the software would not even be able to cause harm to the system. So even though the ecosystem is fragmented, people will eventually have to choose one of the 3 methods for installing apps without using the terminal (doesn't mean one will replace deb files).

As I said earlier, I want this to be more of a discussion rather than a request so this doesn't have to end with a choice. I just wanted to bring some attention to this topic as I believe Linux can become a solid platform for your browser. In the end, the more people that use Cliqz Browser, the better :)

**Comment by remusao** [comment]
@gurgunday Thank you so much for taking to time to detail your thoughts and research on this topic. I am familiar with some of these things but it has been a long while since I took the time to investigate deeply. In principle it would be amazing to have Cliqz packaged in as many ways as possible, so that it can be installed by users on many different systems, and with a variety of technical skills. The choice of Snap/Flatpak/AppImage seems especially attractive in this regard.

Currently we are trying hard to stabilize and improve the Linux build of Cliqz. We operate under limited resources and this is why we chose to focus on building `.deb`, `.rpm`, `.tar.bz2` at the beginning, which should be able to reach many Linux distributions. On top of this, we implemented and maintain our own PPA for Debian/Ubuntu/Linux Mint (this is also something that we can use internally, as multiple Cliqzers use Ubuntu, so it is easier to test and improve for us).

Anything we add on top of these options will require work to ensure that, (1) we make it work, (2) we maintain it in a working condition over time. As a first step, we have started [developing tooling](https://github.com/cliqz-oss/browser-f/pull/1444) to help automatically test that Cliqz can be installed on all flavors of Linux, and also created a new [Wiki page](https://github.com/cliqz-oss/browser-f/wiki/Cliqz-for-Linux) to summarize the current state of Cliqz on Linux. This page contains information about which distributions are supported, how to install Cliqz there, as well as information for people interested in [experimenting with new ways to package Cliqz for Linux](https://github.com/cliqz-oss/browser-f/wiki/Cliqz-for-Linux#faq).

We publish releases in all formats we can: `.deb`, `.rpm`, `.tar.bz2`, so that they can be consumed in many ways (e.g. they are already used to create the [cliqz-bin](https://aur.archlinux.org/packages/cliqz-bin/) Archlinux package). But _we would love some help from the community_ to discuss, and explore new ways to improve the packaging and distribution of Cliqz for Linux. We already have robust infrastructure running to build and release Cliqz, and we continuously improve it (and will continue to do so in the future).

If this is a topic that you are interested in exploring, I would be more than happy to brainstorm about it with you and see how we could best bring Snap, Flatpak, or AppImage to Cliqz. Do you think you could see how a minimal example of packaging Cliqz would look like? It might help to see how it is done for Firefox, since most of this knowledge might also apply to Cliqz as well.

**Comment by ghost** [comment]
Way to communicate with the community! I would love to help in any way, shape, or form. Will check how the packaging can be done in _appimage_ and _snap_ as I'm more familiar with them.

Even though I like the decentralized aspect of flatpak, I believe the others to be better candidates since they are usually preferred by companies to distribute official software. Plus, I found flatpak to be a little harder to use for packaging in general (of course the experience may vary).

Instead of making a choice by thinking which one **_would_** be the best candidate to distribute apps, let's focus on practicality and see which is easier to use in general between the 3.

Edit: By taking a quick look I found a discussion about packaging Firefox with [AppImage](https://bugzilla.mozilla.org/show_bug.cgi?id=1249971). Also, here is the one for [Flatpak](https://bugzilla.mozilla.org/show_bug.cgi?id=1278719).

**Comment by gurgunday** [comment]
I also want to add something real quick. @chrmod seems to have a snap on the Snapstore already. I haven't tried yet but it might help if he has packaged it before.

**Comment by remusao** [comment]
> I also want to add something real quick. @chrmod seems to have a snap on the Snapstore already. I haven't tried yet but it might help if he has packaged it before.

Chrmod is a colleague of mine at Cliqz, and from what I remember at the time he created the account on Snapstore when we experimented with packaging Cliqz. I am pretty sure that I pushed these snaps at the time... but it was not very stable. The situation is probably much better now. From memory, at the time I found the snap for Firefox and adapted it for Cliqz.

Ideally we would create a POC to create a snap, flatpak, app image, based on the tarball of Cliqz (tar.bz2). Also, if the maintenance cost is low enough, we could consider publishing Cliqz to all three stores.

**Comment by remusao** [comment]
@gurgunday This might be interesting here, someone did a POC of building Firefox for both Snap and Flatpak at the same time: https://valentindavid.com/posts/2019-03-27-freedesktop-sdk-snap/.

Source code can be found here: https://gitlab.com/valentindavid/firefox-buildstream/

**Comment by ghost** [comment]
@remusao That’s very cool!

I will do some further research looking into browsers like Beaker and how they packaged it for AppImage with the update mechanism etc. The method used to cover both Snap and Flatpak at the same time _should_ also be applied to Cliqz Browser. So I‘ll also look into building it that way. If you come up with something though, I and probably anyone interested in this topic would very much appreciate it if you shared them here since I might not be that consistent because of... well school.

**Comment by grahamperrin** [comment]
Side note: the port to FreeBSD – [www/cliqz](https://www.freshports.org/www/cliqz/) – seems to work well (for me, with FreeBSD-CURRENT). 

Re: https://svnweb.freebsd.org/ports/head/www/cliqz/Makefile?limit_changes=0&r1=528058&r2=528057&pathrev=528058 (deprecated version of python), I have written to the port maintainer.

**Comment by grahamperrin** [comment]
https://github.com/cliqz-oss/browser-f/issues/1432#issuecomment-578242178

> … find Firefox packaged in all three forms …

FWIW: 

* [Provide an AppImage for Linux · Issue #127 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/127)
* [Provide a Flatpak as software package · Issue #1388 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/1388) (closed, not fixed)
* https://redd.it/6vqjww https://redd.it/ce7fnr https://redd.it/d50mlc (archived) and https://redd.it/dn8h7h
